version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./infra/api/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./api:/usr/src/app/api
    working_dir: /usr/src/app/api
    ports:
      - 8000:80
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./infra/front/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./front:/usr/src/app/front
    working_dir: /usr/src/app/front
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  emulator:
    container_name: emulator
    build:
      context: .
      dockerfile: ./infra/emulator/Dockerfile
    ports:
      - 9001:9001
      - 5001:5001
      - 4000:4000
    tty: true